baseURL = "http://b.neni.dev/"
languageCode = "pt-br"
title = "Lissenin"
description = "Blog com textos e audios em inglês"

[params]
repo = "http://github.com/nenitf/blog_projeto-bilingue"
faviconEmoji = "📚"
